# Generated by Django 5.1.4 on 2025-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroadopcion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fundaciones/'),
        ),
    ]
